// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import RemovalsController from './removals_controller'
application.register('removals', RemovalsController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import FilterFormController from "./filter_form_controller"
application.register("filter-form", FilterFormController)
