upstream app {
    # Path to Puma SOCK file, as defined previously
    server unix:///home/root/apps/okna_perfect/shared/tmp/sockets/okna_perfect-puma.sock;
}

server {
    listen 80;
    listen [::]:80;
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    server_name 142.93.107.113 okna-perfect.cz www.okna-perfect.cz;

    root /home/root/apps/okna_perfect/current/public;

    try_files $uri/index.html $uri @app;

    ssl_certificate /etc/letsencrypt/live/okna-perfect.cz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/okna-perfect.cz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    if ($scheme != "https") {
       return 301 https://okna-perfect.cz$request_uri;
    }

    if ($host ~* ^www\.(.*)) {
       return 301 https://$1$request_uri;
    }

    if ($request_uri ~ "/cgi-sys/defaultwebpage.cgi") {
       return 301 https://okna-perfect.cz;
    }

    location @app {
        proxy_pass http://app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    location /cable {
      proxy_pass http://app/cable;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }

    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 10;
}
